/**
 * Demo mode data — used when NEXT_PUBLIC_DEMO_MODE=true
 * Allows the full app to run without any external services
 */

export const DEMO_MODE = process.env.NEXT_PUBLIC_DEMO_MODE === 'true'

export const DEMO_USER = {
  id: 'demo-user-id',
  email: 'demo@reviewreply.app',
  name: 'Anand Sharma',
  plan: 'pro' as const,
  google_access_token: null,
  google_refresh_token: null,
  google_account_id: null,
  stripe_customer_id: null,
  stripe_subscription_id: null,
  created_at: '2024-01-01T00:00:00Z',
}

export const DEMO_USAGE = {
  id: 'demo-usage-id',
  user_id: 'demo-user-id',
  month: '2025-03',
  ai_replies_used: 27,
  reviews_received: 43,
}

export const DEMO_LOCATIONS = [
  {
    id: 'loc-1',
    user_id: 'demo-user-id',
    google_location_id: 'locations/1234567890',
    name: 'Anand Sweets & Restaurant — MG Road',
    address: '42, MG Road, Bengaluru, Karnataka 560001',
    category: 'Restaurant',
    is_active: true,
    created_at: '2024-01-10T00:00:00Z',
  },
  {
    id: 'loc-2',
    user_id: 'demo-user-id',
    google_location_id: 'locations/9876543210',
    name: 'Anand Sweets & Restaurant — Jayanagar',
    address: '15, 4th Block, Jayanagar, Bengaluru, Karnataka 560011',
    category: 'Restaurant',
    is_active: true,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'loc-3',
    user_id: 'demo-user-id',
    google_location_id: 'locations/1122334455',
    name: 'FreshGlow Spa & Wellness',
    address: '8, Indiranagar 100 Feet Road, Bengaluru, Karnataka 560038',
    category: 'Health & Beauty',
    is_active: true,
    created_at: '2024-02-01T00:00:00Z',
  },
]

export const DEMO_REVIEWS = [
  {
    id: 'rev-1',
    location_id: 'loc-1',
    location_name: 'Anand Sweets — MG Road',
    google_review_id: 'grev-001',
    reviewer_name: 'Priya Krishnamurthy',
    reviewer_photo_url: null,
    rating: 5,
    text: 'Absolutely love this place! The mysore pak and kaju katli are out of this world. Staff is always so warm and friendly. Been coming here for 10 years and the quality never dips. Perfect for festival gifting too!',
    review_language: 'en',
    created_at: '2025-03-15T14:32:00Z',
    synced_at: '2025-03-15T15:00:00Z',
    has_response: false,
    active_response: null,
    responses: [],
  },
  {
    id: 'rev-2',
    location_id: 'loc-1',
    location_name: 'Anand Sweets — MG Road',
    google_review_id: 'grev-002',
    reviewer_name: 'Rahul Menon',
    reviewer_photo_url: null,
    rating: 2,
    text: 'Very disappointed with my recent visit. Waited 20 minutes just to be acknowledged at the counter. The barfi I bought was stale and hard — not what you expect from a premium sweet shop. They need to sort out their customer service urgently.',
    review_language: 'en',
    created_at: '2025-03-14T10:15:00Z',
    synced_at: '2025-03-14T10:30:00Z',
    has_response: false,
    active_response: null,
    responses: [],
  },
  {
    id: 'rev-3',
    location_id: 'loc-2',
    location_name: 'Anand Sweets — Jayanagar',
    google_review_id: 'grev-003',
    reviewer_name: 'Sunita Rao',
    reviewer_photo_url: null,
    rating: 4,
    text: 'Good sweets overall, especially the traditional Karnataka ones. Packaging could be better for gifting purposes — the boxes feel a bit flimsy. But taste is definitely authentic and consistent.',
    review_language: 'en',
    created_at: '2025-03-13T16:45:00Z',
    synced_at: '2025-03-13T17:00:00Z',
    has_response: false,
    active_response: null,
    responses: [],
  },
  {
    id: 'rev-4',
    location_id: 'loc-3',
    location_name: 'FreshGlow Spa',
    google_review_id: 'grev-004',
    reviewer_name: 'Meera Iyer',
    reviewer_photo_url: null,
    rating: 5,
    text: 'Had the most amazing deep tissue massage session. The therapist was incredibly skilled and professional. The ambience is so relaxing — dim lights, calming music, beautiful aromatherapy. Will definitely be back every month!',
    review_language: 'en',
    created_at: '2025-03-12T11:20:00Z',
    synced_at: '2025-03-12T11:30:00Z',
    has_response: true,
    active_response: {
      id: 'resp-4',
      review_id: 'rev-4',
      variant_number: 1,
      text: "Thank you so much for this wonderful feedback, Meera! We're absolutely thrilled that your deep tissue massage was such a rejuvenating experience. Our therapists take great pride in their craft and it's incredibly rewarding to hear that it showed. The atmosphere you described — the dim lights, calming music and aromatherapy — is something we've put a lot of care into creating. We look forward to being your monthly retreat! 🌿",
      status: 'posted',
      posted_at: '2025-03-12T13:00:00Z',
      created_at: '2025-03-12T12:00:00Z',
    },
    responses: [],
  },
  {
    id: 'rev-5',
    location_id: 'loc-1',
    location_name: 'Anand Sweets — MG Road',
    google_review_id: 'grev-005',
    reviewer_name: 'Vikram Nair',
    reviewer_photo_url: null,
    rating: 3,
    text: 'The sweets are decent but the prices have gone up significantly compared to last year. The quality is still good but at these rates I expect better service. The queue management during peak hours is chaotic.',
    review_language: 'en',
    created_at: '2025-03-11T09:30:00Z',
    synced_at: '2025-03-11T10:00:00Z',
    has_response: false,
    active_response: null,
    responses: [],
  },
  {
    id: 'rev-6',
    location_id: 'loc-3',
    location_name: 'FreshGlow Spa',
    google_review_id: 'grev-006',
    reviewer_name: 'Ananya Desai',
    reviewer_photo_url: null,
    rating: 1,
    text: 'Worst experience. Booked an appointment for 3pm, arrived on time, waited 45 minutes and was never called. When I asked, they said there was a mix-up. No apology, no offer to reschedule at a discounted rate. Complete waste of my time. Will never return.',
    review_language: 'en',
    created_at: '2025-03-10T17:00:00Z',
    synced_at: '2025-03-10T17:30:00Z',
    has_response: false,
    active_response: null,
    responses: [],
  },
  {
    id: 'rev-7',
    location_id: 'loc-2',
    location_name: 'Anand Sweets — Jayanagar',
    google_review_id: 'grev-007',
    reviewer_name: 'Karthik Subramaniam',
    reviewer_photo_url: null,
    rating: 5,
    text: 'This branch is our go-to for all celebrations. The halwa here is better than the MG Road branch honestly! The staff recognised us after just 2 visits and remembered our usual order. That personal touch is rare these days.',
    review_language: 'en',
    created_at: '2025-03-09T13:15:00Z',
    synced_at: '2025-03-09T13:30:00Z',
    has_response: false,
    active_response: null,
    responses: [],
  },
  {
    id: 'rev-8',
    location_id: 'loc-1',
    location_name: 'Anand Sweets — MG Road',
    google_review_id: 'grev-008',
    reviewer_name: 'Divya Balachandran',
    reviewer_photo_url: null,
    rating: 4,
    text: 'Great variety and authentic taste. Would have given 5 stars but the parking situation outside is a nightmare. The sweets themselves are excellent — especially the coconut burfi. Ordered a bulk corporate gift box and the delivery was on time.',
    review_language: 'en',
    created_at: '2025-03-08T15:45:00Z',
    synced_at: '2025-03-08T16:00:00Z',
    has_response: false,
    active_response: null,
    responses: [],
  },
]

export const DEMO_STATS = {
  total_reviews: 43,
  pending_reviews: 6,
  responded_reviews: 31,
  skipped_reviews: 6,
  response_rate: 72,
  avg_rating: 4.1,
  reviews_this_month: 12,
  new_reviews_today: 2,
  by_rating: { 1: 3, 2: 4, 3: 7, 4: 15, 5: 14 },
  by_location: [
    { location_id: 'loc-1', location_name: 'MG Road', count: 18, avg_rating: 3.9 },
    { location_id: 'loc-2', location_name: 'Jayanagar', count: 14, avg_rating: 4.3 },
    { location_id: 'loc-3', location_name: 'FreshGlow Spa', count: 11, avg_rating: 4.2 },
  ],
}

export const DEMO_BRAND_VOICE = {
  id: 'bv-1',
  user_id: 'demo-user-id',
  location_id: null,
  tone: 'warm',
  language: 'en',
  owner_name: 'Anand',
  sign_off: 'Warm regards, Anand & Team',
  custom_instructions: 'Always acknowledge specific items or services mentioned. For negative reviews, always offer to make it right. Never be defensive.',
}

export const DEMO_NOTIFICATION_PREFS = {
  id: 'notif-1',
  user_id: 'demo-user-id',
  email_enabled: true,
  email_frequency: 'negative_only',
  whatsapp_enabled: true,
  whatsapp_number: '+91 98765 43210',
  weekly_summary: true,
}

export const DEMO_AI_RESPONSES: Record<string, string[]> = {
  'rev-1': [
    "Thank you so much for your incredibly kind words, Priya! We're overjoyed to hear that our Mysore Pak and Kaju Katli have been delighting you for the past decade — your loyalty means the world to us. Our team works hard to maintain the authentic recipes and quality that we're known for, and hearing that it shows makes all the difference. Wishing you and your family wonderful festival celebrations with our sweets! 🙏",
    "Priya, your review truly made our day! Ten years of trust is something we cherish deeply, and we promise to keep earning it with every bite. Our festival gifting collections are being refreshed for the upcoming season — do ask our team about the premium gift boxes when you visit next. Thank you for being such a valued part of our Anand family! 🍬",
    "What wonderful feedback, Priya! The warmth and quality you've experienced are the two pillars we've built Anand Sweets on. We're so glad the Mysore Pak and Kaju Katli continue to be favourites. Your recommendation for gifting is exactly why we take such pride in our packaging and presentation. See you soon! 🌸",
  ],
  'rev-2': [
    "Dear Rahul, we sincerely apologise for the experience you had during your recent visit — this is truly not the standard we hold ourselves to. A 20-minute wait at the counter and receiving stale barfi is completely unacceptable, and we are deeply sorry. We would very much like to make this right for you. Please reach out to us directly at feedback@anandsweets.in or call +91 80 2345 6789 and we'll personally ensure your next experience is everything you expect from us. Thank you for letting us know.",
    "Rahul, thank you for taking the time to share this feedback, even though we understand how frustrating the experience must have been. We take quality and service very seriously, and the issues you've described — the wait time and the stale barfi — are being investigated with our store team immediately. Please do connect with us so we can make this right. Your trust matters deeply to us.",
  ],
  'rev-5': [
    "Vikram, thank you for your honest feedback. We hear your concern about pricing — the cost of premium ingredients has unfortunately risen across the board, and this has impacted our pricing. We understand this is frustrating. Regarding queue management during peak hours, this is an area we're actively working to improve, including better counter staffing on weekends. We truly value your patronage and hope you'll give us the opportunity to serve you better.",
    "Thank you for sharing this, Vikram. Your feedback on both pricing and peak-hour queue management is genuinely valuable to us. We're rolling out a token system at our counters in the coming weeks to reduce wait times. On pricing — we're committed to offering the best value we can without compromising on quality. We hope to see you again and hear your thoughts after these improvements.",
  ],
  'rev-6': [
    "Ananya, we are truly sorry for what happened. An appointment mix-up with no apology and a 45-minute wait is simply not acceptable, and we completely understand your frustration. This is not the FreshGlow experience we stand for. We are personally reviewing our appointment management system because of incidents like this. We would deeply appreciate the opportunity to make this up to you — please reach out to us at care@freshglowspa.in and we'll arrange a complimentary session at your convenience. We're sorry.",
    "Dear Ananya, there is no excuse for what you experienced. Your time is precious and we wasted it — we own that completely. Appointment mix-ups and the lack of an immediate apology from our team represent a failure we are taking very seriously. We have already spoken to the team involved. Please give us one more chance to show you the real FreshGlow experience — do contact us and we will take care of you personally.",
  ],
}
